### ISSUE TITLE
哆点登录域名

### ISSUE THREAD

**Issue by zombie110year** [Hagb/cqu-duodian-curl#1]
在老校区这边，哆点登录的网址的域名是 `gate.cqu.edu.cn`，IP 是 `202.202.0.163`，虎溪那边可能也是同一个域名。可以用 nslookup 检查一下。

```sh
nslookup 10.254.7.4
```

**Comment by Hagb** [comment]
检查了一下，虎溪这边 `gate.cqu.edu.cn` 的解析结果是 `202.202.0.163`，在上面输入帐号密码能够返回是否登录成功的信息，但没有实际效果（登录后外网没有通）。

虎溪这边通过默认 dns 服务器解析 `dr.com` 可得在虎溪进行哆点验证的 `10.254.7.4`，不知道老校区那边这个域名是否适用？

**Comment by zombie110year** [comment]
```
❯ nslookup dr.com

Non-authoritative answer:
Name:    dr.com
Address:  202.202.0.163
```

老校区的 `dr.com` 的解析结果和 gate 是一样的。
